#!/usr/bin/bash

PYTHON_LIBS=(
    "python-nmap"
    "rich"
    "get-mac"
)

PYTHON_IMPORT_LIBS=(
    "nmap"
    "rich"
    "getmac"
)

TERMINAL_TOOLS=(
    "nmap"
)

RED="\x1b[31m"
CMDC="\x1b[32m"
GREEN="\x1b[34m"
NONE="\x1b[0m"


status="true"

function install_cross_command {
    if [ "$PREFIX" = "" ]; then
        echo -e " '$CMDC$1 $3$NONE'"
    else
        echo -e " '$CMDC$2 $3$NONE'"
    fi
}

function check_tool_installed {
    if ! command -v "$1" &>/dev/null; then
        printf "[$RED FIELD $NONE] $1 tool is not installed try:"
        install_cross_command "sudo apt-get install" "pkg install" $1
        status="false"
    fi
}

function check_python_lib_installed {

    if ! python -c "import $1" &>/dev/null; then
        printf "[$RED FIELD $NONE] $1 tool is not installed try:"
        install_cross_command "pip install" "pip install" $1
        status="false"
    fi
}



for tool in "${TERMINAL_TOOLS[@]}"; do
    check_tool_installed "$tool"
done

for lib in "${PYTHON_IMPORT_LIBS[@]}"; do
    check_python_lib_installed "$lib"
done


if [ "$status" = "true" ]; then
    
    if [ "$EUID" -ne 0 ]; then
       echo -e "[$RED ? $NONE] use 'sudo netinf' to get more info ..."
    fi


    if [ "$PREFIX" = "" ]; then
        python /opt/netinf/netinf.py

    else
        python /data/data/com.termux/files/usr/opt/netinf/netinf.py
    fi
fi
