#!/bin/bash

PYTHON_LIBS=(
    "python-nmap"
    "rich"
    "get-mac"
)

PYTHON_IMPORT_LIBS=(
    "nmap"
    "rich"
    "getmac"
)

TERMINAL_TOOLS=(
    "nmap"
    
)

RED="\x1b[31m"
CMDC="\x1b[32m"
GREEN="\x1b[34m"
NONE="\x1b[0m"


# setup ...
for lib in "${PYTHON_LIBS[@]}"; do
    pip install $lib
done




# check from packages
status="true"

function install_cross_command {
    if [ "$PREFIX" = "" ]; then
        echo -e " '$CMDC$1 $3$NONE'"
    else
        echo -e " '$CMDC$2 $3$NONE'"
    fi
}

function check_tool_installed {
    if command -v "$1" &>/dev/null; then
        echo -e "[$GREEN OK $NONE] $1 tool has been installed ..."
    else
        printf "[$RED FIELD $NONE] $1 tool is not installed try:"
        install_cross_command "sudo apt-get install" "pkg install" $1
        status="false"
    fi
}

function check_python_lib_installed {

    if python -c "import $1" &>/dev/null; then
        echo -e "[$GREEN OK $NONE] $1 lib has been installed ..."
    else
        printf "[$RED FIELD $NONE] $1 tool is not installed try:"
        install_cross_command "pip install" "pip install" $1
        status="false"
    fi
}



for tool in "${TERMINAL_TOOLS[@]}"; do
    check_tool_installed "$tool"
done

for lib in "${PYTHON_IMPORT_LIBS[@]}"; do
    check_python_lib_installed "$lib"
done


if [ "$status" = "true" ]; then
    echo -e "[$CMDC DONE$NONE ] The netinf tool was successfully installed.."
else
   echo -e "[$RED FIELD$NONE ] The installation of netinf tool was not successful."
fi


